### PR TITLE
added .py file that parses json files into a csv for aany state supplied...

### PR DESCRIPTION
**Pull request by jkokenge**
... as cli argument to script.  also added csvs/\* to .gitignore which is where the json-to-csv script outputs generated csvs

Hi David, some reporters here wanted this data out of the json format into a csv file for import into Excel. So, I whipped up a quick json-to-csv.py script.  Then, I figured I'd build it out, quick and dirty like, so that other folks could do the same for other states...should the need arise.  

The usage of the script is pretty straightforward. Run the tool as you've described, then, after the json files have been generated, run the json-to-csv.py script and supply the state to the script via cli argument.  

Let me know what you think.  I can change it however you'd like, make it more robust, etc.  Or, if you don't want it, just let me know that too.  I thought I'd just go ahead and submit the pull request as a rough draft of the idea.

### CODE REVIEW

**Comment by eads** [comment]
Hey Joe, thanks for the submission. We actually had some stuff to do something like this early in the process but it was janky (and not necessary for our story) so it wound up getting cut out.

That said, there's a MUCH easier way to do this, which I'd recommend as an alternative if you have time to code it up. We use the Dataset library, which supports "freezing" queries to CSV: http://dataset.readthedocs.org/en/latest/freezefile.html

Once the data is in the DB, it would be very easy to generate state-by-state CSVs using Dataset's freeze methods, perhaps along with a Freezefile.

**Comment by jkokenge** [comment]
Hey David, thanks!  I'll work on a Dataset based solution.  I've got some free time today and tomorrow and I'll work on knocking that out.  Dataset is very cool and it'll be a good excuse to dig into that.  So, would you recommend getting the data into the DB, then baking out all the csvs into a csvs directory...sort of like what you're doing with the json files?

**Comment by eads** [comment]
Yeah, exactly. And you could just add it to the main processing loop in
process.py -- no need to split it out, since that script already dumps to
the DB for you. Look at how we freeze the agency to CSV

On Thu, Apr 9, 2015 at 12:50 PM, jkokenge <notifications@github.com> wrote:

> Hey David, thanks! I'll work on a Dataset based solution. I've got some
> free time today and tomorrow and I'll work on knocking that out. Dataset is
> very cool and it'll be a good excuse to dig into that. So, would you
> recommend getting the data into the DB, then baking out all the csvs into a
> csvs directory...sort of like what you're doing with the json files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nprapps/ucr-clearance-parser/pull/10#issuecomment-91288784>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Comment by jkokenge** [comment]
Cool. I'll back this out and resubmit.  I see what you're talking about now.  Thanks man!

**Comment by jkokenge** [comment]
Hey man, after contemplating this, I realized probably what you realized in the first place....that there's no reason to write Python to execute SQL to export data that already exists in a database and can be exported right from there.  I was so keen to hack on this that I missed the forest for the trees here.  Anyway, good tool man.  And a good reason to dig into your code. Thanks!

**Comment by eads** [comment]
Heh, right. Well, it still makes sense to write Python, I think. Writing
EXPORT SQL statements in a bash script is a little ugly. That's what we did
for the 1033 data (https://github.com/nprapps/leso). It works, but Dataset
makes life a lot easier by providing a reasonable DB abstraction for the
kind of data work journalists do in Python. But there's definitely no
reason to consume the use-case-specific JSON files. Then you're just
reconstructing what's already in the DB from a more complex format using a
slower process.  Instead, just write queries and use Dataset to serialize
them to CSV.

Thanks for the interest! If I have some time I'd like to train CSVKit to
consume UMich's tab separated clearance rate files, which would give us a
much longer historical perspective.

On Thu, Apr 9, 2015 at 8:23 PM, jkokenge <notifications@github.com> wrote:

> Hey man, after contemplating this, I realized probably what you realized
> in the first place....that there's no reason to write Python to execute SQL
> to export data that already exists in a database and can be exported right
> from there. I was so keen to hack on this that I missed the forest for the
> trees here. Anyway, good tool man. And a good reason to dig into your code.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nprapps/ucr-clearance-parser/pull/10#issuecomment-91387347>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow

**Pull request closed without merging**
